# Generated by Django 4.0.4 on 2022-04-25 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currencyName', models.CharField(max_length=100)),
                ('currencyRate', models.FloatField()),
                ('date', models.DateField(default='2022-04-25')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=200)),
                ('date', models.DateField(default='2022-04-25')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventoryPart', models.CharField(max_length=200)),
                ('inventoryImage', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description', models.TextField(blank=True)),
                ('unitMeasure', models.CharField(blank=True, choices=[('Cartons', 'Cartons'), ('Pieces', 'Pieces')], max_length=100)),
                ('costPrice', models.FloatField()),
                ('sellingPrice', models.FloatField()),
                ('percentageProfit', models.CharField(max_length=150)),
                ('stockValue', models.CharField(max_length=150)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendorSupplied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plumbing.vendor')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ['-inventoryPart'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=200)),
                ('contact', models.CharField(blank=True, max_length=150)),
                ('quantity', models.IntegerField(default=1)),
                ('rate', models.CharField(max_length=100)),
                ('totalAmountPaid', models.FloatField()),
                ('balance', models.FloatField()),
                ('order_status', models.CharField(choices=[('Complete', 'Complete'), ('Pending', 'Pending'), ('Incomplete', 'Incomplete')], max_length=20)),
                ('modeOfPayment', models.CharField(max_length=100)),
                ('date', models.DateField(default='2022-04-25')),
                ('addedby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('item_purchased', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plumbing.stock')),
            ],
        ),
    ]
