# Generated by Django 4.0.4 on 2022-05-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='unitMeasure',
        ),
        migrations.AddField(
            model_name='customer',
            name='due_date',
            field=models.DateField(blank=True, default='2022-05-07'),
        ),
        migrations.AddField(
            model_name='customer',
            name='purchased_From',
            field=models.CharField(choices=[('firdous', 'firdous'), ('sj', 'sj')], default='sj', max_length=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='cartonQuantity',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='stock',
            name='piecesQuantity',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateField(default='2022-05-07'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='date',
            field=models.DateField(default='2022-05-07'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='date',
            field=models.DateField(default='2022-05-07'),
        ),
    ]
