# Generated by Django 4.0.4 on 2022-05-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0003_alter_customer_date_alter_customer_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='percentageProfit',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
