# Generated by Django 4.0.4 on 2022-05-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0004_alter_stock_percentageprofit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateField(default='2022-05-09'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='due_date',
            field=models.DateField(blank=True, default='2022-05-09', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='modeOfPayment',
            field=models.CharField(choices=[('Bank', 'Bank'), ('Cash', 'Cash')], max_length=100),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='date',
            field=models.DateField(default='2022-05-09'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='date',
            field=models.DateField(default='2022-05-09'),
        ),
    ]
