# Generated by Django 4.0.4 on 2022-05-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0005_alter_customer_date_alter_customer_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='rate',
        ),
    ]
