# Generated by Django 4.0.4 on 2022-05-12 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0007_cheques_remove_stock_stockvalue_alter_customer_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cheques',
            options={'ordering': ['-expenseName'], 'verbose_name': 'Cheque', 'verbose_name_plural': 'Cheques'},
        ),
    ]
