# Generated by Django 4.0.4 on 2022-05-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0010_alter_cashinvoice_date_alter_cheques_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashinvoice',
            name='chooseAccount',
        ),
        migrations.AddField(
            model_name='cashinvoice',
            name='modeOfPayment',
            field=models.CharField(choices=[('Bank', 'Bank'), ('Cash', 'Cash')], default='Cash', max_length=100),
        ),
        migrations.AddField(
            model_name='payable',
            name='Balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='payable',
            name='chooseAccount',
            field=models.CharField(choices=[('firdous', 'firdous'), ('sj', 'sj')], default='sj', max_length=200),
        ),
        migrations.AddField(
            model_name='payable',
            name='modeOfPayment',
            field=models.CharField(choices=[('Bank', 'Bank'), ('Cash', 'Cash')], default='Cash', max_length=100),
        ),
        migrations.AddField(
            model_name='payable',
            name='status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Pending', 'Pending'), ('Incomplete', 'Incomplete')], default='Pending', max_length=20),
        ),
    ]
