# Generated by Django 4.0.4 on 2022-05-22 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0011_remove_cashinvoice_chooseaccount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payable',
            old_name='totalAmountPaid',
            new_name='amountToPay',
        ),
        migrations.RemoveField(
            model_name='cheques',
            name='chequeId',
        ),
        migrations.RemoveField(
            model_name='payable',
            name='Balance',
        ),
        migrations.RemoveField(
            model_name='payable',
            name='chooseAccount',
        ),
        migrations.RemoveField(
            model_name='payable',
            name='modeOfPayment',
        ),
        migrations.RemoveField(
            model_name='payable',
            name='status',
        ),
        migrations.AlterField(
            model_name='cashinvoice',
            name='date',
            field=models.DateField(default='2022-05-22'),
        ),
        migrations.AlterField(
            model_name='cheques',
            name='date',
            field=models.DateField(default='2022-05-22'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateField(default='2022-05-22'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='due_date',
            field=models.DateField(blank=True, default='2022-05-22', null=True),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='date',
            field=models.DateField(default='2022-05-22'),
        ),
        migrations.AlterField(
            model_name='payable',
            name='date',
            field=models.DateField(default='2022-05-22'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='date',
            field=models.DateField(default='2022-05-22'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='date',
            field=models.DateField(default='2022-05-22'),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modeOfPayment', models.CharField(choices=[('Bank', 'Bank'), ('Cash', 'Cash')], default='Cash', max_length=100)),
                ('amountPaid', models.FloatField()),
                ('chooseAccount', models.CharField(choices=[('firdous', 'firdous'), ('sj', 'sj')], default='sj', max_length=200)),
                ('Balance', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('Complete', 'Complete'), ('Pending', 'Pending'), ('Incomplete', 'Incomplete')], default='Pending', max_length=20)),
                ('date', models.DateField(default='2022-05-22')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plumbing.payable')),
            ],
        ),
    ]
