# Generated by Django 4.0.4 on 2022-05-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0013_alter_cashinvoice_date_alter_cheques_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheques',
            name='id',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='id',
        ),
        migrations.AddField(
            model_name='cheques',
            name='chequeId',
            field=models.AutoField(default=6, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='transfer',
            name='InvoiceNumber',
            field=models.AutoField(default=6, primary_key=True, serialize=False),
        ),
    ]
