# Generated by Django 4.0.4 on 2022-05-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0014_remove_cheques_id_remove_transfer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheques',
            name='chequeId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='InvoiceNumber',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
