# Generated by Django 4.0.4 on 2022-05-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0015_alter_cheques_chequeid_alter_transfer_invoicenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheques',
            name='chequeId',
            field=models.AutoField(default=10000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='InvoiceNumber',
            field=models.AutoField(default=10000, primary_key=True, serialize=False),
        ),
    ]
