# Generated by Django 4.0.4 on 2022-05-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0016_alter_cheques_chequeid_alter_transfer_invoicenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheques',
            name='chequeId',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='InvoiceNumber',
        ),
        migrations.AddField(
            model_name='cheques',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='id',
            field=models.BigAutoField(auto_created=True, default=3, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
