# Generated by Django 4.0.4 on 2022-06-14 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0020_cashinvoice_currency_cheques_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashinvoice',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='cheques',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='currency',
        ),
    ]
