# Generated by Django 4.0.4 on 2022-06-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0021_remove_cashinvoice_currency_remove_cheques_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cashAccount', models.FloatField()),
                ('bankAccount', models.FloatField()),
                ('debtorBalance', models.FloatField()),
                ('accountBalance', models.FloatField()),
                ('expensesTotal', models.FloatField()),
                ('grandTotal', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
