# Generated by Django 4.0.4 on 2022-06-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0022_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cashFromReceipts',
            field=models.FloatField(blank=True, default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='totalAmountPaid',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='amountPaid',
            field=models.FloatField(default=0.0),
        ),
    ]
