# Generated by Django 4.0.4 on 2022-08-08 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0023_account_cashfromreceipts_alter_customer_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashinvoice',
            name='date',
            field=models.DateField(default='2022-08-08'),
        ),
        migrations.AlterField(
            model_name='cheques',
            name='date',
            field=models.DateField(default='2022-08-08'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateField(default='2022-08-08'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='due_date',
            field=models.DateField(blank=True, default='2022-08-08', null=True),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='date',
            field=models.DateField(default='2022-08-08'),
        ),
        migrations.AlterField(
            model_name='payable',
            name='date',
            field=models.DateField(default='2022-08-08'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='date',
            field=models.DateField(default='2022-08-08'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='date',
            field=models.DateField(default='2022-08-08'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='date',
            field=models.DateField(default='2022-08-08'),
        ),
        migrations.CreateModel(
            name='CustomerReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiptNumber', models.CharField(max_length=150)),
                ('customerName', models.CharField(max_length=150)),
                ('modeOfPayment', models.CharField(default='Cash', max_length=100)),
                ('purchasedFrom', models.CharField(blank=True, default=0, max_length=150)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.CharField(blank=True, default=0, max_length=150)),
                ('discount', models.FloatField(default=0.0)),
                ('totalAmountPaid', models.FloatField()),
                ('AmountAfterDiscount', models.FloatField()),
                ('balance', models.FloatField()),
                ('date', models.DateField(default='2022-08-08')),
                ('item_purchased', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plumbing.stock')),
            ],
        ),
    ]
