# Generated by Django 4.0.4 on 2022-08-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0024_alter_cashinvoice_date_alter_cheques_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashinvoice',
            name='date',
            field=models.DateField(default='2022-08-09'),
        ),
        migrations.AlterField(
            model_name='cheques',
            name='date',
            field=models.DateField(default='2022-08-09'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateField(default='2022-08-09'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='due_date',
            field=models.DateField(blank=True, default='2022-08-09', null=True),
        ),
        migrations.AlterField(
            model_name='customerreceipt',
            name='balance',
            field=models.CharField(blank=True, default=0, max_length=150),
        ),
        migrations.AlterField(
            model_name='customerreceipt',
            name='date',
            field=models.DateField(default='2022-08-09'),
        ),
        migrations.AlterField(
            model_name='customerreceipt',
            name='discount',
            field=models.CharField(blank=True, default=0, max_length=150),
        ),
        migrations.AlterField(
            model_name='customerreceipt',
            name='item_purchased',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='customerreceipt',
            name='quantity',
            field=models.CharField(blank=True, default=0, max_length=150),
        ),
        migrations.AlterField(
            model_name='customerreceipt',
            name='totalAmountPaid',
            field=models.CharField(blank=True, default=0, max_length=150),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='date',
            field=models.DateField(default='2022-08-09'),
        ),
        migrations.AlterField(
            model_name='payable',
            name='date',
            field=models.DateField(default='2022-08-09'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='date',
            field=models.DateField(default='2022-08-09'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='date',
            field=models.DateField(default='2022-08-09'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='date',
            field=models.DateField(default='2022-08-09'),
        ),
    ]
